name: flow
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0=pyhd3eb1b0_1
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.8=h06a4308_0
  - cachetools=4.2.0=pyhd3eb1b0_0
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.4=py37h261ae71_0
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.1.2=py_0
  - cryptography=3.3.1=py37h3c74f83_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=py_0
  - intel-openmp=2020.2=254
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.3=py37h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1i=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - pip=20.3.1=py37h06a4308_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py37_0
  - pyopenssl=20.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - requests=2.25.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - setuptools=51.0.0=py37h06a4308_2
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorflow=2.2.0=mkl_py37h6e9ce2d_0
  - tensorflow-base=2.2.0=mkl_py37hd506778_0
  - tk=8.6.10=hbc83047_0
  - werkzeug=1.0.1=py_0
  - wheel=0.36.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - astor==0.8.1
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==20.3.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.3
    - blessings==1.7
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - colorful==0.5.4
    - cycler==0.10.0
    - decorator==4.4.2
    - dm-tree==0.1.5
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.2.2
    - google==3.0.0
    - google-api-core==1.23.0
    - google-auth==1.24.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.34.0
    - gym==0.17.3
    - hiredis==1.1.0
    - importlib-metadata==3.1.1
    - imutils==0.5.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jsonschema==3.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lxml==4.6.2
    - lz4==3.1.1
    - matplotlib==3.3.3
    - msgpack==1.0.1
    - multidict==5.1.0
    - numpy==1.19.4
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.11
    - opencensus-context==0.1.2
    - opencv-python==4.4.0.46
    - opencv-python-headless==4.3.0.36
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - py-spy==0.3.3
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - ray==1.0.1
    - redis==3.4.1
    - scipy==1.4.1
    - soupsieve==2.1
    - tabulate==0.8.7
    - tensorboard==2.0.2
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - yarl==1.6.3
prefix: /scratch/cluster/wmacke/anaconda3_2/envs/flow_test_ray1.0.1
